
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_backend
    command: gunicorn --bind 0.0.0.0:8000 store.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    env_file:
      - .env
    networks:
      - app-network

  celery:
    build: .
    container_name: celery
    command: celery -A store worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - backend
    networks:
      - app-network
      
 

  redis:
    image: redis:6-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network


  front_end:
    build:
      context: ../front_end
      dockerfile: Dockerfile
    container_name: front_docker
    volumes:
      - ../front_end:/app
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge